import {
  colors,
  fonts,
  combineSelectors,
  cssSelectorsToString,
  brightness
} from "./common";

const selectors = [
  "a",
  "button",
  "input[type='submit']",
  "input[type='button']",
];

export default {
  buttonColorStyle: (color) =>
    cssSelectorsToString({
      [combineSelectors(selectors, `.nyx-button-${color}`)]: {
        paddingTop: "4px",
        paddingBottom: "4px",
        paddingLeft: "10px",
        paddingRight: "10px",
        textAlign: "center",
        borderRadius: "6px",
        borderWidth: "1px",
        borderStyle: "solid",
        display: "inline-block",
        letterSpacing: "1.5px",
        fontFamily: fonts.default,
        fontSize: "12px",
        textShadow: `0px 0px 3px ${colors.background}`,
        cursor: "pointer",
        margin: "2px",
        userSelect: "none",
        textDecoration: "none",
        outline: "none",
        backgroundColor: colors.brightness(colors[color], brightness.darkest),
        borderColor: colors[color],
        color: colors.brightness(colors[color], brightness.light),
      },
      [combineSelectors(selectors, `.nyx-button-${color}:hover`)]: {
        color: colors.brightness(colors[color], brightness.light),
        backgroundColor: colors.brightness(colors[color], brightness.dark),
      },
      [combineSelectors(selectors, `.nyx-button-${color}:active`)]: {
        backgroundColor: colors.brightness(colors[color], brightness.dark),
        color: colors.brightness(colors[color], brightness.light),
      },
      [combineSelectors(selectors, `.nyx-button-active-${color}`)]: {
        paddingTop: "4px",
        paddingBottom: "4px",
        paddingLeft: "10px",
        paddingRight: "10px",
        textAlign: "center",
        borderRadius: "6px",
        borderWidth: "1px",
        borderStyle: "solid",
        display: "inline-block",
        letterSpacing: "1.5px",
        fontFamily: fonts.default,
        fontSize: "12px",
        textShadow: `0px 0px 3px ${colors.background}`,
        cursor: "pointer",
        margin: "2px",
        userSelect: "none",
        textDecoration: "none",
        outline: "none",
        borderColor: colors[color],
        backgroundColor: colors.brightness(colors[color], brightness.dark),
        color: colors.brightness(colors[color], brightness.light),
      },
      [combineSelectors(selectors, `.nyx-button-active-${color}:hover`)]: {
        color: colors.brightness(colors[color], brightness.light),
        backgroundColor: colors.brightness(colors[color], brightness.dark),
      },
      [combineSelectors(selectors, `.nyx-button-active-${color}:active`)]: {
        backgroundColor: colors.brightness(colors[color], brightness.dimest),
        borderColor: colors[color],
        color: colors.brightness(colors[color], brightness.lightest),
      },
      [combineSelectors(selectors, `.nyx-button-disabled-${color}`)]: {
        paddingTop: "4px",
        paddingBottom: "4px",
        paddingLeft: "10px",
        paddingRight: "10px",
        textAlign: "center",
        borderRadius: "6px",
        borderWidth: "1px",
        borderStyle: "solid",
        display: "inline-block",
        letterSpacing: "1.5px",
        fontFamily: fonts.default,
        fontSize: "12px",
        textShadow: `0px 0px 3px ${colors.background}`,
        margin: "2px",
        cursor: "default",
        userSelect: "none",
        textDecoration: "none",
        outline: "none",
        backgroundColor: colors.brightness(colors[color], brightness.darkest),
        borderColor: colors.brightness(colors[color], brightness.dimest),
        color: colors.brightness(colors[color], brightness.dimest),
      },
      [combineSelectors(selectors, `.nyx-button-disabled-${color}:hover`)]: {
        color: colors.brightness(colors[color], brightness.dimest),
      },
    }),
  default: cssSelectorsToString({
    "button, input[type='submit'], input[type='button']": {
      color: colors.brightness(colors.standard, brightness.light),
      backgroundColor: colors.brightness(colors.standard, brightness.darkest),
      paddingTop: "4px",
      paddingBottom: "4px",
      paddingLeft: "10px",
      paddingRight: "10px",
      textAlign: "center",
      borderRadius: "6px",
      borderWidth: "1px",
      borderStyle: "solid",
      display: "inline-block",
      letterSpacing: "1.5px",
      fontFamily: fonts.default,
      fontSize: "12px",
      textShadow: `0px 0px 3px ${colors.background}`,
      cursor: "pointer",
      margin: "2px",
      userSelect: "none",
      textDecoration: "none",
      outline: "none",
      borderColor: colors.standard,
    },
    "button:hover, input[type='submit']:hover, input[type='button']:hover": {
      color: colors.brightness(colors.standard, brightness.light),
      backgroundColor: colors.brightness(colors.standard, brightness.dark),
    },
    "button:active, input[type='submit']:active, input[type='button']:active": {
      backgroundColor: colors.brightness(colors.standard, brightness.dark),
      color: colors.brightness(colors.standard, brightness.light),
    },
  }),
};
