import {
  colors,
  fonts,
  combineSelectors,
  cssSelectorsToString,
} from "./common";

const selectors = [
  "a",
  "button",
  "input[type='submit']",
  "input[type='button']",
];

export default {
  buttonColorStyle: (color) =>
    cssSelectorsToString({
      [combineSelectors(selectors, `.nyx-button-${color}`)]: {
        paddingTop: "4px",
        paddingBottom: "4px",
        paddingLeft: "10px",
        paddingRight: "10px",
        textAlign: "center",
        borderRadius: "6px",
        borderWidth: "1px",
        borderStyle: "solid",
        display: "inline-block",
        letterSpacing: "1.5px",
        fontFamily: "Helvetica, Arial",
        fontSize: "12px",
        textShadow: `0px 0px 3px ${colors.background}`,
        cursor: "pointer",
        margin: "2px",
        userSelect: "none",
        textDecoration: "none",
        outline: "none",
        backgroundColor: colors.brightness(colors[color], -200),
        borderColor: colors[color],
        color: colors.brightness(colors[color], 40),
      },
      [combineSelectors(selectors, `.nyx-button-${color}:hover`)]: {
        color: colors.brightness(colors[color], 40),
        backgroundColor: colors.brightness(colors[color], -175),
      },
      [combineSelectors(selectors, `.nyx-button-${color}:active`)]: {
        backgroundColor: colors.brightness(colors[color], -150),
        color: colors.brightness(colors[color], 40),
      },
      [combineSelectors(selectors, `.nyx-button-active-${color}`)]: {
        paddingTop: "4px",
        paddingBottom: "4px",
        paddingLeft: "10px",
        paddingRight: "10px",
        textAlign: "center",
        borderRadius: "6px",
        borderWidth: "1px",
        borderStyle: "solid",
        display: "inline-block",
        letterSpacing: "1.5px",
        fontFamily: "Helvetica, Arial",
        fontSize: "12px",
        textShadow: `0px 0px 3px ${colors.background}`,
        cursor: "pointer",
        margin: "2px",
        userSelect: "none",
        textDecoration: "none",
        outline: "none",
        borderColor: colors[color],
        backgroundColor: colors.brightness(colors[color], -150),
        color: colors.brightness(colors[color], 40),
      },
      [combineSelectors(selectors, `.nyx-button-active-${color}:hover`)]: {
        color: colors.brightness(colors[color], 40),
        backgroundColor: colors.brightness(colors[color], -125),
      },
      [combineSelectors(selectors, `.nyx-button-active-${color}:active`)]: {
        backgroundColor: colors.brightness(colors[color], -100),
        borderColor: colors[color],
        color: colors.brightness(colors[color], 80),
      },
      [combineSelectors(selectors, `.nyx-button-disabled-${color}`)]: {
        paddingTop: "4px",
        paddingBottom: "4px",
        paddingLeft: "10px",
        paddingRight: "10px",
        textAlign: "center",
        borderRadius: "6px",
        borderWidth: "1px",
        borderStyle: "solid",
        display: "inline-block",
        letterSpacing: "1.5px",
        fontFamily: fonts.default,
        fontSize: "12px",
        textShadow: `0px 0px 3px ${colors.background}`,
        margin: "2px",
        cursor: "default",
        userSelect: "none",
        textDecoration: "none",
        outline: "none",
        backgroundColor: colors.brightness(colors[color], -200),
        borderColor: colors.brightness(colors[color], -100),
        color: colors.brightness(colors[color], -100),
      },
      [combineSelectors(selectors, `.nyx-button-disabled-${color}:hover`)]: {
        color: colors.brightness(colors[color], -100),
      },
    }),
  default: cssSelectorsToString({
    "button, input[type='submit'], input[type='button']": {
      color: colors.brightness(colors.standard, 40),
      backgroundColor: colors.brightness(colors.standard, -200),
      paddingTop: "4px",
      paddingBottom: "4px",
      paddingLeft: "10px",
      paddingRight: "10px",
      textAlign: "center",
      borderRadius: "6px",
      borderWidth: "1px",
      borderStyle: "solid",
      display: "inline-block",
      letterSpacing: "1.5px",
      fontFamily: fonts.default,
      fontSize: "12px",
      textShadow: `0px 0px 3px ${colors.background}`,
      cursor: "pointer",
      margin: "2px",
      userSelect: "none",
      textDecoration: "none",
      outline: "none",
      borderColor: colors.standard,
    },
    "button:hover, input[type='submit']:hover, input[type='button']:hover": {
      color: colors.brightness(colors.standard, 40),
      backgroundColor: colors.brightness(colors.standard, -175),
    },
    "button:active, input[type='submit']:active, input[type='button']:active": {
      backgroundColor: colors.brightness(colors.standard, -150),
      color: colors.brightness(colors.standard, 40),
    },
  }),
};
